name: Combine Dependabot PRs

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-dependabot-prs:
    if: github.repository == 'gradle/common-custom-user-data-gradle-plugin'
    runs-on: ubuntu-latest
    steps:
      - name: combine-dependabot-prs
        uses: github/combine-prs@v3.1.1
        with:
          branch_regex: ^(dependa|wrapper)bot\/.*$
          github_token: ${{ secrets.GITHUB_TOKEN }}
